/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quan_ly_sinh_vien;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import static quan_ly_sinh_vien.User.DocFile;

/**
 *
 * @author MAN NGHI
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bnDangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtDangKy = new javax.swing.JButton();
        bnhienpass = new javax.swing.JButton();
        anhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(300, 300, 300, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ĐĂNG NHẬP HỆ THỐNG");
        jLabel1.setMaximumSize(new java.awt.Dimension(580, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bnDangNhap.setBackground(new java.awt.Color(204, 204, 204));
        bnDangNhap.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bnDangNhap.setText("Đăng Nhập");
        bnDangNhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        bnDangNhap.setMaximumSize(new java.awt.Dimension(580, 400));
        bnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(bnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 169, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("User :");
        jLabel2.setMaximumSize(new java.awt.Dimension(580, 400));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 55, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Password :");
        jLabel3.setMaximumSize(new java.awt.Dimension(580, 400));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 106, -1, -1));

        txtUser.setBackground(new java.awt.Color(0, 153, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        txtUser.setMaximumSize(new java.awt.Dimension(580, 400));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 72, 185, -1));

        txtPass.setBackground(new java.awt.Color(0, 153, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        txtPass.setMaximumSize(new java.awt.Dimension(580, 400));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 103, 185, -1));

        txtDangKy.setBackground(new java.awt.Color(204, 204, 204));
        txtDangKy.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtDangKy.setText("Đăng Ký");
        txtDangKy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        txtDangKy.setMaximumSize(new java.awt.Dimension(580, 400));
        txtDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDangKyActionPerformed(evt);
            }
        });
        getContentPane().add(txtDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, -1, -1));

        bnhienpass.setBackground(new java.awt.Color(204, 204, 204));
        bnhienpass.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bnhienpass.setText("Hiện Pass");
        bnhienpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        bnhienpass.setMaximumSize(new java.awt.Dimension(580, 400));
        bnhienpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnhienpassActionPerformed(evt);
            }
        });
        getContentPane().add(bnhienpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 169, -1, -1));

        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tải xuống.jpg"))); // NOI18N
        anhnen.setMaximumSize(new java.awt.Dimension(580, 400));
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 300, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnDangNhapActionPerformed
        // TODO add your handling code here:
        LinkedList<User> l = new LinkedList<User>();
        DocFile(l);
        String username = txtUser.getText();
        String password = new String(txtPass.getPassword());

        boolean found = false;

        for (User user : l) {
            if (user.getUserName().equals(username) && user.getPassWord().equals(password)) {
                found = true;
                break;
            }
        }

        if (found) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
            this.dispose();
            new fromQuanLySinhVien().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng. Vui lòng thử lại!");
            // Xóa trắng trường nhập mật khẩu và tài khoản
            txtUser.setText("");
            txtPass.setText("");
            // Đặt con trỏ vào trường tên người dùng để người dùng có thể tiếp tục nhập
            txtUser.requestFocusInWindow();
        }
    }//GEN-LAST:event_bnDangNhapActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
        txtPass.requestFocusInWindow();

    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem các trường đã được điền đầy đủ chưa
        boolean allFieldsFilled = !txtUser.getText().isEmpty() && !new String(txtPass.getPassword()).isEmpty();

        // Nếu có trường chưa điền, di chuyển đến trường đó và hiển thị thông báo lỗi
        if (!allFieldsFilled) {
            if (txtUser.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên người dùng!");
                txtUser.requestFocusInWindow();
            } else if (new String(txtPass.getPassword()).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!");
                txtPass.requestFocusInWindow();
            }
        } else {
            // Nếu tất cả các trường đã được điền đầy đủ, thực hiện hành động cho nút Đăng ký
            bnDangNhap.doClick();
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDangKyActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangKy dk = new DangKy();
        dk.setVisible(true);
    }//GEN-LAST:event_txtDangKyActionPerformed

    private boolean DaHienThi = false;
    private void bnhienpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnhienpassActionPerformed
        // TODO add your handling code here:
        // Đảo ngược trạng thái của biến boolean
        DaHienThi = !DaHienThi;
        // Hiển thị hoặc ẩn mật khẩu dựa trên trạng thái của biến
        if (DaHienThi) {
            txtPass.setEchoChar((char) 0); // Hiển thị mật khẩu
        } else {
            txtPass.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_bnhienpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap DangNhapForm = new DangNhap();
                DangNhapForm.setLocationRelativeTo(null); // Hiển thị JFrame ở giữa màn hình
                DangNhapForm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhnen;
    private javax.swing.JButton bnDangNhap;
    private javax.swing.JButton bnhienpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton txtDangKy;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
